baseURL = 'https://jjmstark.github.io/my-blog/'
languageCode = 'en-us'
title = '0xStark'
theme = 'PaperMod'

[params]
  env = "production"
  title = ""
  description = "Welcome to my personal blog"
  keywords = ["blog", "personal", "hugo"]
  author = "Josh Stark"
  
  # Theme settings
  defaultTheme = "auto"
  disableThemeToggle = false
  disableScrollToTop = true
  
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  
  # Home page settings
  homeInfoParams.Title = "About"
  homeInfoParams.Content = "This is the website of **Josh Stark** where I write about Ethereum, blockchains, and the futures we can build with them. I am particularly interested in understanding and articulating why blockchains can be worthy of trust, and how this proprety can be compared existing infrastructure. \n\n&nbsp;\n\nI work for [Ethereum](https://ethereum.org/) at the [Ethereum Foundation](https://ethereum.foundation/) as a member of the management team. Previously I co-founded [ETHGlobal](https://ethglobal.com/) and [L4](https://x.com/L4ventures/status/1006543147290292224?s=20).\n\n&nbsp;\n\n[X](https://x.com/0xstark) | [Farcaster](https://farcaster.xyz/0xstark.eth)"


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
    
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
